language: java
jdk:
  - oraclejdk8
install: mvn clean compile sonar:sonar  -Dsonar.organization=tregmor-github  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=192c4b571ff72b497875514a17ac572527140541
